### ISSUE TITLE
[Bug]: casting event ProductNotification to Product throw error

### ISSUE THREAD

**Issue by jobcespedes** [PaddleHQ/paddle-node-sdk#26] opened 2024-04-26 00:43 UTC
### What happened?

Getting casting error from ProductNotification to Product
```
Property 'prices' is missing in type 'ProductNotification' but required in type 'Product'.ts
```

### Steps to reproduce

1. Cast from ProductNotification to Product

### What did you expect to happen?

ProductNotification becomes a Product entity for storage purposes

### Logs

```shell
Property 'prices' is missing in type 'ProductNotification' but required in type 'Product'.ts
```

**Comment by vijayasingam-paddle** [comment] 2024-04-26 10:25
Hi @jobcespedes,
Thank you for raising this bug report.

The notification classes and their API counterparts are different by design.

When we introduce a non-nullable field to the API, all the events that occurred before this change will be missing the field. To prevent any runtime errors, all new non-nullable fields in the API entity will be marked as optional in the Notification entity. 

In this instance, you can optionally include `prices` in a Product. However, it will never be available in Product related events. So the missing `prices` property in `ProductNotification` is valid. 

You could try typecasting the `ProductNotification` to the `Product` class, but I would be very wary as typecasting removes some type safety and could lead to runtime issues. 


<img width="764" alt="product-typecasting" src="https://github.com/PaddleHQ/paddle-node-sdk/assets/100207323/714f3cf5-7324-4232-b1d7-70faf7b6fb5b">

**Closed** 2024-04-26 17:21 UTC
