### ISSUE TITLE
[Bug]: Not supported to run in Cloudflare Worker Edge environment

### ISSUE THREAD

**Issue by wytxer** [PaddleHQ/paddle-node-sdk#37] opened 2024-07-05 15:13 UTC
### What happened?

Using the Next.js 14 + TypeScript tech stack, with the API set to the edge environment, an error occurs when calling paddle.transactions.create after importing the @paddle/paddle-node-sdk package: Module build failed: UnhandledSchemeError: Reading from "node:crypto".

### Steps to reproduce

Reproduction code snippet:

```ts
// route.ts

import { Environment, Paddle } from '@paddle/paddle-node-sdk'

export const runtime = 'edge'

const paddle = new Paddle(process.env.PADDLE_SECRET_KEY!, {
  environment: Environment.production,
})

const transaction = await paddle.transactions.create({
  items: [
    {
      quantity: 1,
      priceId: 'priceId',
    },
  ],
})

```

### What did you expect to happen?

I hope to use @paddle/paddle-node-sdk in an edge environment.

### Logs

```shell
⨯ node:crypto
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:crypto
node_modules/@paddle/paddle-node-sdk/dist/esm/internal/api/client.js
node_modules/@paddle/paddle-node-sdk/dist/esm/paddle.js
node_modules/@paddle/paddle-node-sdk/dist/esm/index.js
```

**Comment by vijayasingam-paddle** [comment] 2024-07-05 15:52
Hi @wytxer,
Thank you for opening this bug report with all the details. 
I am sorry that you are running into this issue.

Our node SDK was built for Node.js Runtime, as Edge runtime [uses web API](https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes) some of the dependencies we use like the `crypto` module will not work.

Even though removing the `node:` prefix might solve the problem for you, I fear it will break for others. So that is not an option.

I will find a solution to this problem and get back to you once it is released.

Thank you.

**Comment by wytxer** [comment] 2024-07-06 01:15
Thank you for your reply. I am building a product based on Cloudflare Worker. Is there a plan for when it will be released?

**Comment by westlinkin** [comment] 2024-07-09 02:18
@vijayasingam-paddle I'm trying to implement paddle in Cloudflare workers, As you mentioned,

> We do support CloudFlare workers using NodeJS runtime.

I'm planning to use Cloudflare workers as the backend, so could you let me know if this works?

**Comment by vijayasingam-paddle** [comment] 2024-07-09 11:21
Hi @westlinkin,
Yes, our SDK works in CloudFlare workers using NodeJS runtime. 
This issue is relevant only to the Edge runtime

Please feel free to reach out to us if you face any difficulties while integrating with your application.

Thank you.

**Comment by richhost** [comment] 2024-07-22 14:16
Oh, I use CloudFlare Worker as the backend, `node:crypto` prevents me continuing

**Comment by vijayasingam-paddle** [comment] 2024-07-23 09:35
Hi @richhost, 
We haven't made any progress on this yet. As we had not planned to support this, it is taking longer to prepare for this change. 

Meanwhile, can you please try version `1.2.2`? We were using `crypto` as a dependency at this point so it might work for you. 
There are a few functional differences between `1.2.2` and the latest version. You can read through our [Changelog](https://github.com/PaddleHQ/paddle-node-sdk/blob/main/CHANGELOG.md) to find the differences

I will get back to you once a proper fix is released. 

Thank you.

**Comment by wytxer** [comment] 2024-07-31 01:04
> Hi @wytxer, I am afraid that it will take a while for us to change this as we had not planned to run our SDK using web APIs and supporting both runtimes will be tricky.
> 
> We do support CloudFlare workers using NodeJS runtime. However, looking at your snippet, you are deploying a NextJS app to CloudFlare workers which as I understand can only run on an edge runtime.
> 
> If you don't mind me asking, is there any particular reason not to deploy this in Vercel or Netlify where the infra plays well with NextJS applications compared to CF workers?
> 
> Thank you.

Because the website that is already online is based on Cloudflare Worker, migrating the entire site to a platform like Vercel to use the Paddle API would be very costly.

**Comment by wytxer** [comment] 2024-07-31 01:10
> @vijayasingam-paddle I'm trying to implement paddle in Cloudflare workers, As you mentioned,
> 
> > We do support CloudFlare workers using NodeJS runtime.
> 
> I'm planning to use Cloudflare workers as the backend, so could you let me know if this works?

Bro, you can consider trying the version I forked: https://github.com/wytxer/paddle-node-sdk. I changed crypto to crypto-js, and one of my projects is using it. The API is completely consistent with the official version. You can click to check my modification history.

`npm i @wytxer/paddle-node-sdk`

**Comment by Abel1011** [comment] 2024-08-03 00:44
Hello, you could try this in your next.config.js:

```
webpack: (config) => {
    config.externals.push({
      'node:crypto': 'commonjs crypto',
    });
    return config;
  },
```

**Comment by arfath-linklet** [comment] 2024-10-09 08:29
I see 2.0.0-rc.0 supports edge runtime. Can vijayasingam-paddle recommend the same temporarily?

**Comment by danbillson** [comment] 2024-10-15 16:56
Hey @arfath-linklet, of course the v2 release candidate can't be confirmed as completely stable but we're more than happy for you to give it a go and let us know if you run into any issue

**Comment by lukeed** [comment] 2024-11-12 17:01
This can be closed as it's a Cloudflare problem, which they've now solved.

Add this to your `wranger.toml` file:

```
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
# or
compatibility_flags = [ "nodejs_compat_v2" ]
```
> **Docs:**
> https://developers.cloudflare.com/workers/runtime-apis/nodejs/
> https://developers.cloudflare.com/workers/configuration/compatibility-flags/#nodejs-compatibility-flag

**Comment by lukeed** [comment] 2024-11-20 18:37
Vercel Edge is Cloudflare Workers
Netlify / Supabase / Deno Deploy are all Deno (with 100% Node compat)

---

As mentioned, this is now moot since 2.0 has RuntimeProviders that brings/uses different crypto imports.

**Comment by danbillson** [comment] 2024-11-21 17:22
Going to close this issue as this is now supported in the `2.0.0` release, thanks all for your input on this

**Closed by danbillson** 2024-11-21 17:22 UTC
